version: '3'
services:
  mysql:
    image: mysql:5.7
    command: "--explicit_defaults_for_timestamp"
    volumes:
      - ./tmp/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: UserName
      MYSQL_DATABASE: DatabaseName
      MYSQL_PASSWORD: Password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  key-retrieval:
    build:
      context: .
      args:
        branch: docker-compose
        revision: docker-compose
        component: key-retrieval
    ports:
      - "8001:8001"
    cap_drop:
      - ALL
    depends_on:
      - mysql
    restart: always
    environment:
      ECDSA_KEY: "You can use the main.go inside cmd/generate-ecdsa-private-key to generate this"
      DATABASE_URL: UserName:Password@tcp(mysql)/DatabaseName
      RETRIEVE_HMAC_KEY: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      METRIC_PROVIDER: stdout
      TRACER_PROVIDER: 
      KEY_CLAIM_TOKEN: TokenUsedToVerifyClaimRequest
  key-submission:
    build:
      context: .
      args:
        branch: docker-compose
        revision: docker-compose
        component: key-submission
    ports:
      - "8000:8000"
    cap_drop:
      - ALL
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    depends_on:
      - mysql
    restart: always
    environment:
      DATABASE_URL: UserName:Password@tcp(mysql)/DatabaseName
      KEY_CLAIM_TOKEN: "TokenUsedToVerifyClaimRequest"
      METRIC_PROVIDER: ""
      TRACER_PROVIDER: ""
      METRICS_USERNAME: 1234567890
      METRICS_PASSWORD: 1234567890