version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached   
    command: sleep infinity
    ports: 
      - 8000:8000
      - 8001:8001
    links: 
      - db
    environment: 
      DB_USER: test
      DB_PASS: password
      DB_HOST: db
      DB_NAME: test
      DB_PORT: 3306
      DATABASE_URL: "test:password@tcp(db)/test"
      ECDSA_KEY: You can use the main.go inside cmd/generate-ecdsa-private-key to generate this
      KEY_CLAIM_TOKEN: TokenUsedToVerifyClaimRequest
      RETRIEVE_HMAC_KEY: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      METRICS_USERNAME: 1234567890
      METRICS_PASSWORD: 1234567890
    
  db:
    image: mysql:5.7
    restart: on-failure
    ports: 
      - 3310:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
